from hyper_velocity_stars_detection.variables_names import (
    BP_RP,
    G_MAG,
    PARALLAX,
    PARALLAX_ERROR,
    PM_DEC,
    PM_DEC_ERROR,
    PM_RA,
    PM_RA_ERROR,
)

ERROR_COLUMNS = [PARALLAX_ERROR, PM_DEC_ERROR, PM_RA_ERROR]
DEFAULT_COLS = [PARALLAX]
CMD_COLUMNS = [BP_RP, G_MAG]
DEFAULT_COLS_CLUS = [PARALLAX, PM_RA, PM_DEC, BP_RP, G_MAG]
DEFAULT_ITERATIONS = 500
MAX_SAMPLE_OPTIMIZE = 20000
MAX_CLUSTER_DEFAULT = 10
