PARALLAX = "parallax"
G_LATITUDE = "b"
G_LONGITUDE = "l"
RA = "ra"
DEC = "dec"
PM_RA = "pmra"
PM_DEC = "pmdec"
PM_RA_KMS = "pmra_kms"
PM_DEC_KMS = "pmdec_kms"
PM_G_LATITUDE = "pm_b"
PM_G_LONGITUDE = "pm_l"
PM_G_LATITUDE_KMS = "pm_b_kms"
PM_G_LONGITUDE_KMS = "pm_l_kms"
PM_RA_ERROR = "pmra_error"
PM_DEC_ERROR = "pmdec_error"
PARALLAX_ERROR = "parallax_error"
BP_RP = "bp_rp"
G_MAG = "phot_g_mean_mag"
PM_KMS = "pm_kms"
PM = "pm"


ASTRO_OBJECT = "astro_object"
ASTRO_OBJECT_DATA = "astro_data"
GLOBULAR_CLUSTER_ANALYSIS = "globular_cluster"
XRSOURCE = "xrsource"
CLUSTERING_RESULTS = "clustering_results"
CLUSTERING_DETECTION = "clustering"
